# Numpy
What is NumPy?

NumPy stands for:
Numerical Python

It is a library for:

* Fast numerical computation
* Arrays
* Matrix operations
* Linear algebra
* Scientific computing.

In [1]:
print("Hello")

Hello


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np
arr = np.array([[10,20,30,40,50],
               [60,70,80,90,100]])
print(arr.shape)
print(arr.size)
print(arr.ndim)

(2, 5)
10
2


In [10]:
arr = np.array([[1,2],
              [3,4],
              [5,6]])
print(arr.shape)
print(arr.dtype)

(3, 2)
int64


In [ ]:
arr = np.zeros((4,4))
print(arr)
arr = np.ones((2,5))
print(arr)

In [15]:
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
arr = np.linspace(0,100,11)
print(arr)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [27]:
arr= np.array([
 [90,85,88],
 [70,65,72],
 [95,92,97]
])
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Total Elements:", arr.size)

Shape: (3, 3)
Dimensions: 2
Total Elements: 9


In [31]:
arr = np.array([[90,85,88],[70,65,72],[95,92,97]])
print("Highest marks:", np.max(arr))
print("Lowest marks:", np.min(arr))
print("Average marks:", np.mean(arr))
print("Student2 marks:", arr[1])
print("English Marks of all students:", arr[:,2])

Highest marks: 97
Lowest marks: 65
Average marks: 83.77777777777777
Student2 marks: [70 65 72]
English Marks of all students: [88 72 97]


In [ ]:
arr = np.array([10,20,30,40,50])
print(arr + 5)
print(arr * 3)
print(arr ** 2)

[15 25 35 45 55]
[ 30  60  90 120 150]
[ 100  400  900 1600 2500]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]
150


np.int64(10)

In [39]:
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

150
30.0
50
10


In [41]:
students = np.array([
 [90,85,88],
 [70,65,72],
 [95,92,97],
 [80,75,78]
])
print("Shape:", students.shape)
print("Total Elements:", students.size)
print("Avg per student:", np.mean(students,axis = 1))
print("Avg per subject:", np.mean(students,axis = 0))
print("Highest marks:", np.max(students,axis = 0))
print("Lowest marks", np.min(students,axis = 0))
print("Reshape:", students.reshape(2,6))
print("Bonus marks:", students + 5)


Shape: (4, 3)
Total Elements: 12
Avg per student: [87.66666667 69.         94.66666667 77.66666667]
Avg per subject: [83.75 79.25 83.75]
Highest marks: [95 92 97]
Lowest marks [70 65 72]
Reshape: [[90 85 88 70 65 72]
 [95 92 97 80 75 78]]
Bonus marks: [[ 95  90  93]
 [ 75  70  77]
 [100  97 102]
 [ 85  80  83]]
